# -*- coding: utf-8 -*-
"""Atividade senai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0F-nTLrCUSSntrjduB0oUVSuUi8yAgo

Exercício 1
"""

print("Preciso contar os tijolos que estão empilhados, estimo ter +75 tijolos")
for poste in range(1,101):
  print(poste)

"""Exercício 2"""

print("Os postes pares que irei pintar de 1 a 50 são:")
for par in range(2,51,2):
  print(par)

"""Exercício 3"""

print("Os corredores com número ímpares serão contemplados com um kit especial, serão eles os corredores de número: ")
for impar in range(1,100,2):
  print(f"O corredore de número {impar} receberá o kit especial")

"""Exercício 4"""

soma = 0
for contador in range(5):
  num = float(input("Digite quanto cada um contribuirá: "))
  soma += num
media = soma/5
print(f"A média da vaquinha será de R$ {media}")
print(f"A soma total da vaquinha será de R${soma}")

"""Exercício 5"""

for numero in range (1,10,2):
  print(f"Os números ímpares de 1 a 10 serão: {numero}")

for numero in range (2,11,2):
  print(f"Os números pares de 1 a 10 serão: {numero}")

"""Exercício 6"""

numero = int(input("Insira o número que deseja saber a tabuada: "))
for tabuada in range(1, 11):
  resultado = numero * tabuada
  print(f"{numero} X {tabuada} = {resultado}")

"""Exercício 7"""

for tabuada in range(1,11):
  print(f"Tabuada do {tabuada}")
  for numero in range(1,11):
    resultado = tabuada * numero
    print(f"{numero} X {tabuada} = {resultado}")

"""Exercício 8"""

for placa in range(1,21):
  print(placa)
for lado in range(1,21):
    print(lado, end=' ')

"""Exercício 9"""

print("Os livros ímpares de 1 a 50 serão os de número: ")
for impar in range(1,50,2):
  print(f"Os livros de número ímpar serão os: {impar}")

"""Exercício 10"""

num1 = int(input("Coloque um número inteiro: "))
num2 = int(input("Coloque outro número inteiro: "))
for inteiro in range(num1, num2 +1):
  print(inteiro)

"""Exercício 11"""

lucro = 0
for faturamento in range(5):
  num = float(input("Digite o valor da venda R$ "))
  lucro += num
print(f"O lucro total será de R${lucro}")

if lucro > 54.000:
  print(f"O total das vendas superou R$54.000,00. Superando em {lucro-54000}")
else:
  print("A loja não faturou mais que R$54.000,00")

"""Exercício 12"""

for robo1 in range(2,21,2):
  robo2 = robo1 + 1
  print(f"O robô {robo1} está correndo com o robô {robo2}. Eles estão correndo juntos!")

"""Exercício 13"""

for numero in range(1000,2001):
  if numero % 11 == 2:
   print(numero)

"""Exercício 14"""

for contador in range(10,0,-1):
  print(contador)
print("Lançar Foguete!")

"""Exercício 15"""

soma = 0
for cofrinho in range(30):
  moeda = float(input(f"Digite o valor da moeda do dia {cofrinho + 1} R$"))
  soma += moeda
print(f"A soma total do cofrinho será de R${soma}")

"""Exercício 16"""

pesadao = 0
for boi in range(5):
  peso = float(input(f"Digite o peso do {boi + 1}° Boi: "))
  if peso > pesadao:
     pesadao = peso

print(f"O Boi mais pesado pesa {pesadao} kg")

"""Exercício 17"""

import datetime

salario = float(input("Digite o salário em 1995 R$"))
ano_inicio = 1995
ano_atual = 2025
percentual_aumento = 1.5

print(f"Ano: {ano_inicio} - Salário inicial R${salario}")

for ano in range(ano_inicio, ano_atual + 1):
    salario += salario * (percentual_aumento / 100)
    print(f"Ano {ano}: Salário = R$ {salario:.2f}")
    percentual_aumento *= 2

"""Exercício 18"""

qtproduto = 0
for produto in range(10):
  qtfinal = int(input(f"Insira a quantidade em estoque do {produto + 1}° produto: "))
  qtproduto += qtfinal
print(f"A quantidade total de produtos no estoque é de {qtproduto} unidades")

"""Exercício 19"""

soma = 0
dia_quente = 0
dia_frio = 0
temp_quente = float('-inf')
temp_fria = float('inf')

for dias in range(7):
    temp = int(input(f"Qual foi a temperatura do {dias + 1}° dia? "))

    soma += temp

    if temp > temp_quente:
        temp_quente = temp
        dia_quente = dias + 1


    if temp < temp_fria:
        temp_fria = temp
        dia_frio = dias + 1

media = soma / 7

print(f"A média das temperaturas é: {media:.2f}°C")
print(f"O dia mais quente foi o {dia_quente}° dia com {temp_quente}°C")
print(f"O dia mais frio foi o {dia_frio}° dia com {temp_fria}°C")

"""Exercício 20"""

for i in range(1, 101):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)