# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smn3hDIVBj-Pm_hfGHtP_bsjb1o04KLI

# PYTHON
"""

print ("Olá Mundo!!!")



"""Exercicio 1"""

X1 = 6 + 4 * 2
X2 = (4 * 9 + 5)
X3 = ((6 + 7) * 9)
X4 = (15 + 20 - 30)
X5 = (6 + 5**2)

print(X1, X2, X3, X4, X5)

"""EXERCICIO 2"""

numero_1 = 5
numero_1 += 5
print(numero_1)

# Para alterar o valor que será somado é só verificar a linha em que ele se encontra, EX: Na linha 2, o número "1 = 5" será somado com a segunda linha

"""EXERCICIO 3"""

cofrinho = 8

cofrinho += 5
print(cofrinho)
cofrinho -= 4
print(cofrinho)
cofrinho *= 20
print(cofrinho)
cofrinho /= 2
print(cofrinho)

# Sempre justificar com "print()" para exibir o valor individualmente

"""EXERCICIO 4"""

numero_1 = 2
numero_2 = 4
soma = numero_1 + numero_2
if (soma < 10):
 print ("Soma nãoé maior que 10")

#São três variáveis, sendo n°1, n°2 e soma. Caso utlizando o "IF" deve-se dar um espaço para não ter erros.

"""EXERCICIO 5"""

soma_1 = 7 + 8
soma_2 = 10 + 5
if (soma_2 == soma_1):
  print("Os resultados são iguais")

"""EXERCICIO 6"""

X = 8
X1 = 3

# Analisar a comparação das variaveis

Resultado = X < X1
print (Resultado)

Resultado = X == X1
print (Resultado)

Resultado = X >= X1
print (Resultado)

Resultado = X != X1
print(Resultado)

'''
Não é necessário usar if e nem aspas, está sendo utilizado para "LER" o comando.
'''

"""EXERCICIO 7"""

idade_lucas = 20
idade_carolina = 17

if(idade_lucas >= 18 or idade_carolina >= 18):
  print("Pelo menos um dos dois é maior de idade")
if(idade_lucas >= 18 and idade_carolina < 18):
  print("Só Lucas é maior de idade")
if(idade_lucas < 18 and idade_carolina >= 18):
  print("Só Carolina é maior de idade")
if(idade_lucas < 18 and idade_carolina < 18):
  print("Nenhum dos dois é maior de idade")


#Usar "if" para comparação e "or" para comparar dentro de um comando, serve como um "OU" e "and" como "E"
#No Python é usado and / No C é usado $$
#No Python é usado or / No C é usado ||
#No Python é usado and / No C é usado !

"""EXERCICIO 8"""

time_carlos = 'Botafogo'
time_luciano = 'Flamengo'
time_fabricia = 'Botafogo'

print(time_carlos is time_fabricia)

x = 'botafogo'
x1 = 'flamengo'
x3 = 'botafogo'

Xresult = x is x3
print(Xresult)
Xresult = x is not x3
print(Xresult)
Xresult = x1 is x3
print(Xresult)
Xresult = x1 is not x3
print(Xresult)

# No Python "is" é dado como "É ou Igual" e "not" é dado como "Não"

"""EXERCICIO 9"""

frutas = ["banana", "laranja", "uva", "ameixa"]

fruta_1 = "ameixa"
fruta_2 = "melancia"

print(fruta_1 in frutas) #True
print(fruta_2 in frutas) #False

X = 4
X1 = 9
X2 = 5
XResult = (((2 + 5) * 3) + X + 5) < X1
print(XResult)

XResult = (((2 + 5)* 3) + (X + 5 < X1) == (X == 6 + X2 * 2))
print(XResult)

XResult = (((3 * 6) + X - 3) < X2)
print(XResult)

XResult = (((7 * 8) > (X + 4 > X1) < (X != 2 + X2 * 9)))
print(XResult)

"""EXERCICIO 10"""

nota1 = float(input('Digite sua nota: '))
nota2 = float(input('Digite sua nota: '))
media = (nota1 + nota2) /2
if media <7:
  print("O Aluno não foi aprovado!")
if media >=7:
  print('O Aluno foi Aprovado!')

# "Float" é numero quebrado, já "int" é número inteiro

número = int(input('Digite um número: '))

if número >=30:
 print('O número é maior que 30')
else:
 print('O número é menor que 30')

 # "If" é "se" e "else" seria "senão". E "else" só pode ser utilizado acompanhado do "if"

"""EXERCICIO 11"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))

#Calcular a média aritmética
media = (nota1 + nota2)/2

#Verificar se o aluno foi aprovado
if media >= 7:
  print(f"O Aluno foi aprovado! Média {media:.2f}")

#Verificar uma outra condição
elif media >= 5:
  print(f"O Aluno está em recuperação! Media {media:.2f}")

#Verifica se o aluno foi reprovado
else:
  print(f"O aluno foi reprovado! Média {media}")

# Utilizar ":.2f" para se ter 2 casas decimais e assim sucessivamente.

a = int(input("Digite um número: "))

if a >= 50:
  print("O número", a, "é maior ou igual a 50")

else:
  print(f"O número {a: .2f} é menor que 50")

"""EXERCICIO 12"""

a = int(input("Informe um número entre 0 e 100: "))
if a > 50:
  print("O número", a,"é maior que 50.")
elif a == 50:
  print("O número informado é igual a 50.")
else:
  print ("O número", a,"é menor que 50.")

# É utilizado o "elif" para verificar se o valor informado é igual a X. Elif é uma condição, sendo usado para acrescentar um "porém" no código.

alimento_selecionado = "arroz"

if alimento_selecionado == "arroz":
  print("Vamos jantar " + alimento_selecionado)
elif alimento_selecionado == "macarrão":
  print("vamos jantar " + alimento_selecionado)
else:
  print("O item não consta na lista")

# Saiba ler e configurar os códigos para conseguir colocar os "poréns" em sua configuração

"""EXERCICIO 13"""

